pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh '''cd "$(find . -name pom.xml -type f -printf '%h' -quit)"'''
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}